apiVersion: v1
kind: Service
metadata:
  name: ping-service
spec:
  selector:
    app: ping
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5200
      targetPort: 5200
      nodePort: 30000
